name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Log Tests
        run: echo "Running Playwright tests"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run e2e:ci
      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Upload Playwright snapshot diffs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-snapshots
          path: |
            test-results/
            e2e/snapshots/
          if-no-files-found: warn

# One of these actions will likely come in handy...
# https://github.com/marketplace/actions/background-action
# https://github.com/marketplace/actions/background-run-test