name: Format, Lint and Typecheck

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ main, next ]

jobs:
  format-lint-typecheck:
    timeout-minutes: 15
    runs-on: ubuntu-slim
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
          node-version: lts/*

      - name: Install Node.js dependencies
        run: npm ci

      - name: Formatting and linting with Biome
        run: npm run biome

      - name: TypeScript Type Check
        run: npx tsc --noEmit