name: Workflow dispatch update snapshots.

on:
  workflow_dispatch:  # so you can run it manually

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run e2e:ci

      - name: Commit snapshot changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Committing snapshot changes to PR branch ${{ github.ref_name }}"
          git config user.name MapTiler Testbot
          git add -A
          git commit -am "[BOT] Update snapshots (Triggered by @${{ github.event.comment.user.login }})" || echo "No changes to commit"
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} $CURRENT_BRANCH

