name: Workflow dispatch update snapshots.

on:
  workflow_dispatch:  # so you can run it manually

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get PR number
        id: get_pr
        uses: actions/github-script@v6
        with:
          script: return context.payload.issue.pull_request.number

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ steps.get_pr.outputs.result }}/head
          fetch-depth: 0
          persist-credentials: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run e2e:ci-update

      - name: Commit snapshot changes
        run: |
          echo "Committing snapshot changes to PR branch ${{ github.ref_name }}"
          git config user.name MapTiler Testbot
          git add -A
          git commit -am "[BOT] Update snapshots (Triggered by @${{ github.event.comment.user.login }})" || echo "No changes to commit"
          git push origin HEAD:refs/heads/${{ steps.get_pr.outputs.result }}
