name: Slash Commands
on:
  issue_comment:
    types: [created]
jobs:
  run:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/update-snapshots')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Playwright tests"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --update-snapshots
